name: Clean Old Mocks # Name of the workflow (you'll see this in GitHub Actions tab)

on:
  schedule:
    - cron: "30 18 * * *" # Every day 18:30 UTC = 12:00 AM IST
  workflow_dispatch: # Allow manual trigger from GitHub UI

jobs:
  cleanup: # Define a job named "cleanup"
    runs-on: ubuntu-latest # Use GitHub's Ubuntu virtual machine

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        # Pulls your repository code into the Ubuntu VM

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install mongoose
        run: npm install mongoose
        # Install mongoose dependency

      - name: Run cleanup script
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: node BackEnd/cleanUp.js
        # Runs the cleanup.js script
